<?php
$pageTitle = 'Generate Formal Request';
include __DIR__ . '/../partials/layout_head.php';

$requestId = intval($_GET['id'] ?? 0);
if (!$requestId) {
    echo '<div class="alert alert-danger">Invalid request.</div>';
    include __DIR__ . '/../partials/layout_foot.php';
    exit;
}

$srModel  = new ServiceRequest($conn);
$proposal = $srModel->getById($requestId);

// Security: must belong to this organizer and must be barangay_approved
if (!$proposal || $proposal['user_id'] != $_SESSION['user']['id'] || $proposal['status'] !== 'barangay_approved') {
    echo '<div class="alert alert-danger">This proposal is not available for formal request generation.</div>';
    include __DIR__ . '/../partials/layout_foot.php';
    exit;
}

// Check if formal request already submitted
$chk = $conn->prepare("SELECT id FROM formal_requests WHERE request_id = ?");
$chk->execute([$requestId]);
$existing = $chk->fetch();
if ($existing) {
    echo '<div class="alert alert-warning"><i class="bi bi-info-circle me-2"></i>A formal request has already been submitted for this proposal. <a href="index.php?action=my_requests">Go back</a></div>';
    include __DIR__ . '/../partials/layout_foot.php';
    exit;
}

$pmModel   = new PlantingMaterial($conn);
$materials = $pmModel->getAll();

// Handle submission
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $required = ['proponent_name','recipient_name','recipient_position','seedling_variety','quantity_requested','activity_date','activity_location','purpose'];
    $missing  = false;
    foreach ($required as $f) {
        if (empty(trim($_POST[$f] ?? ''))) { $missing = true; break; }
    }

    if ($missing) {
        $error = 'Please fill in all required fields.';
    } else {
        $stmt = $conn->prepare("
            INSERT INTO formal_requests
                (request_id, user_id, proponent_name, association_name, recipient_name,
                 recipient_position, seedling_variety, quantity_requested,
                 activity_date, activity_time, activity_location, purpose)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ");
        $result = $stmt->execute([
            $requestId,
            $_SESSION['user']['id'],
            trim($_POST['proponent_name']),
            trim($_POST['association_name'] ?? ''),
            trim($_POST['recipient_name']),
            trim($_POST['recipient_position']),
            trim($_POST['seedling_variety']),
            intval($_POST['quantity_requested']),
            $_POST['activity_date'],
            $_POST['activity_time'] ?? null,
            trim($_POST['activity_location']),
            trim($_POST['purpose']),
        ]);

        if ($result) {
            // Update service request status
            $srModel->updateStatus($requestId, 'formal_request_submitted', 'Formal request generated by organizer.');

            // Notify affairs workers
            $affairsWorkers = (new User($conn))->getAllByRole('community_affairs_worker');
            $notifModel     = new Notification($conn);
            $senderName     = htmlspecialchars($_SESSION['user']['firstname'] . ' ' . $_SESSION['user']['lastname']);
            foreach ($affairsWorkers as $aw) {
                $notifModel->create($aw['id'], 'New Formal Request',
                    "$senderName submitted a formal request for proposal {$proposal['request_number']}. Please verify stock availability.");
            }
            $success = true;
        } else {
            $error = 'Failed to submit formal request. Please try again.';
        }
    }
}
?>

<div class="ps-page-header">
    <h2>Generate Formal Request</h2>
    <p>Process 3 — Fill in the formal request details for your approved proposal.</p>
</div>

<!-- Proposal summary banner -->
<div class="alert d-flex align-items-start gap-3 mb-4"
     style="background:#f0faf0;border:1px solid #b7dfb7;border-radius:12px;padding:16px 20px;">
    <i class="bi bi-check-circle-fill text-success mt-1" style="font-size:1.2rem;"></i>
    <div>
        <div class="fw-bold text-success mb-1">Proposal Approved by Barangay Captain</div>
        <div class="small text-muted">
            <strong><?= htmlspecialchars($proposal['request_number']) ?></strong> —
            <?= htmlspecialchars($proposal['activity_name']) ?> |
            <?= htmlspecialchars($proposal['target_location']) ?> |
            <?= date('M d, Y', strtotime($proposal['target_date'])) ?>
        </div>
    </div>
</div>

<?php if (!empty($success)): ?>
    <div class="alert alert-success d-flex align-items-center gap-2">
        <i class="bi bi-check-circle-fill"></i>
        <div>Formal request submitted successfully! The Community Affairs Worker will now verify stock availability.
            <a href="index.php?action=my_requests" class="alert-link ms-2">View My Proposals →</a>
        </div>
    </div>
<?php else: ?>

<?php if (isset($error)): ?>
    <div class="alert alert-danger d-flex align-items-center gap-2">
        <i class="bi bi-exclamation-circle-fill"></i>
        <span><?= htmlspecialchars($error) ?></span>
    </div>
<?php endif; ?>

<form method="POST" action="index.php?action=formal_request&id=<?= $requestId ?>">

    <!-- Proponent Info -->
    <div class="ps-card mb-4">
        <h6 class="fw-bold text-ps-green mb-3">
            <i class="bi bi-person me-2"></i>Proponent Information
        </h6>
        <div class="row mb-3">
            <div class="col-md-6">
                <label class="form-label">Proponent Name <span class="text-danger">*</span></label>
                <input type="text" name="proponent_name" class="form-control"
                       value="<?= htmlspecialchars($_POST['proponent_name'] ?? ($proposal['proponent_name'] ?? ($_SESSION['user']['firstname'] . ' ' . $_SESSION['user']['lastname']))) ?>"
                       required>
            </div>
            <div class="col-md-6">
                <label class="form-label">Association / Organization Name</label>
                <input type="text" name="association_name" class="form-control"
                       value="<?= htmlspecialchars($_POST['association_name'] ?? ($proposal['association_name'] ?? '')) ?>"
                       placeholder="e.g. Barangay Farmers Association">
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <label class="form-label">Recipient Name <span class="text-danger">*</span></label>
                <input type="text" name="recipient_name" class="form-control"
                       value="<?= htmlspecialchars($_POST['recipient_name'] ?? ($proposal['recipient_name'] ?? '')) ?>"
                       placeholder="Name of recipient officer" required>
            </div>
            <div class="col-md-6">
                <label class="form-label">Recipient Position / Title <span class="text-danger">*</span></label>
                <input type="text" name="recipient_position" class="form-control"
                       value="<?= htmlspecialchars($_POST['recipient_position'] ?? ($proposal['recipient_position'] ?? '')) ?>"
                       placeholder="e.g. Municipal Agriculture Officer" required>
            </div>
        </div>
    </div>

    <!-- Seedling / Material Request -->
    <div class="ps-card mb-4">
        <h6 class="fw-bold text-ps-green mb-3">
            <i class="bi bi-tree me-2"></i>Seedling / Material Request
        </h6>
        <div class="row">
            <div class="col-md-6 mb-3">
                <label class="form-label">Seedling Variety / Name <span class="text-danger">*</span></label>
                <select name="seedling_variety" class="form-select" required>
                    <option value="" disabled <?= empty($_POST['seedling_variety']) ? 'selected' : '' ?>>Select seedling variety</option>
                    <?php
                    $plantingList = [
                        'Banana Lakatan','Avocado','Marang','Durian','Lanzones',
                        'Rambutan','Jackfruit','Corn','Coffee','Cacao','Vegetable Seeds'
                    ];
                    $matLookup = [];
                    foreach ($materials as $m) $matLookup[$m['material_name']] = $m;
                    $selectedVariety = $_POST['seedling_variety'] ?? $proposal['seedling_type'] ?? '';
                    foreach ($plantingList as $pName):
                        $mat = $matLookup[$pName] ?? null;
                        $qtyLabel = ($mat && $mat['quantity'] > 0)
                            ? ' (' . number_format($mat['quantity']) . ' ' . htmlspecialchars($mat['unit']) . ' available)'
                            : '';
                    ?>
                        <option value="<?= htmlspecialchars($pName) ?>"
                            <?= $selectedVariety === $pName ? 'selected' : '' ?>>
                            <?= htmlspecialchars($pName) ?><?= $qtyLabel ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div class="col-md-6 mb-3">
                <label class="form-label">Quantity Requested <span class="text-danger">*</span></label>
                <input type="number" name="quantity_requested" class="form-control"
                       min="1" placeholder="Number of seedlings/packs"
                       value="<?= htmlspecialchars($_POST['quantity_requested'] ?? $proposal['quantity_requested']) ?>"
                       required>
            </div>
        </div>
    </div>

    <!-- Activity Details -->
    <div class="ps-card mb-4">
        <h6 class="fw-bold text-ps-green mb-3">
            <i class="bi bi-calendar-event me-2"></i>Activity Details
        </h6>
        <div class="row mb-3">
            <div class="col-md-4">
                <label class="form-label">Activity Date <span class="text-danger">*</span></label>
                <input type="date" name="activity_date" class="form-control"
                       value="<?= htmlspecialchars($_POST['activity_date'] ?? $proposal['target_date']) ?>"
                       required>
            </div>
            <div class="col-md-4">
                <label class="form-label">Activity Time</label>
                <input type="time" name="activity_time" class="form-control"
                       value="<?= htmlspecialchars($_POST['activity_time'] ?? ($proposal['activity_time'] ?? '08:00')) ?>">
            </div>
            <div class="col-md-4">
                <label class="form-label">Location / Site <span class="text-danger">*</span></label>
                <input type="text" name="activity_location" class="form-control"
                       value="<?= htmlspecialchars($_POST['activity_location'] ?? $proposal['target_location']) ?>"
                       placeholder="Barangay, Municipality" required>
            </div>
        </div>
    </div>

    <!-- Purpose -->
    <div class="ps-card mb-4">
        <h6 class="fw-bold text-ps-green mb-3">
            <i class="bi bi-chat-left-text me-2"></i>Purpose / Justification
        </h6>
        <textarea name="purpose" class="form-control" rows="4" required
                  placeholder="Describe the purpose of this formal request..."><?= htmlspecialchars($_POST['purpose'] ?? $proposal['purpose']) ?></textarea>
    </div>

    <div class="d-flex gap-2">
        <button type="submit" class="btn btn-ps-primary">
            <i class="bi bi-send me-2"></i>Submit Formal Request
        </button>
        <a href="index.php?action=my_requests" class="btn btn-outline-secondary">Cancel</a>
    </div>

</form>
<?php endif; ?>

<?php include __DIR__ . '/../partials/layout_foot.php'; ?>
